# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install libraries
        run: pip install -r ./libraries/requirements.txt
      
      - name: Test the python executable
        run: |
          pwd
          cd ./code
          python -m unittest tests.send_message_test
          
          
  terraform:  
    name: 'Terraform'    
    needs: build_and_test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform    
    
    steps:         
    
    - name: Checkout  
      uses: actions/checkout@v2          

    - name: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:   
      # terraform_version: 0.13.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  
    
    - name: Terraform Init
      id: init 
      run: terraform init
    
    - name: Terraform Validate
      id: validate  
      run: terraform validate -no-color
      
    - name: Terraform Plan   
      id: plan 
      if: github.event_name == 'pull_request' 
      run: terraform plan -no-color 
      continue-on-error: true

    #creates a comment about the terraform plan inside the merge request 
    - name: Update Pull Request  
      uses: actions/github-script@0.9.0 
      if: github.event_name == 'pull_request' 
      env:    
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}" 
      with:   
        github-token: ${{ secrets.GITHUB_TOKEN }}   
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\` 
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`  
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`  
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
      
          <details><summary>Show Plan</summary>
      
          \`\`\`\n      ${process.env.PLAN}      \`\`\`
      
          </details>
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,   
            repo: context.repo.repo,  
            body: output   
          })

    - name: Terraform Plan Status 
      if: steps.plan.outcome == 'failure' 
      run: exit 1

    - name: Terraform Apply
      env:
        DYNAMO_ACCESS_KEY_ID: ${{ secrets.DYNAMO_ACCESS_KEY_ID }}
        DYNAMO_SECRET_ACCESS_KEY: ${{ secrets.DYNAMO_SECRET_ACCESS_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'  
      run: terraform apply -auto-approve -var="key=$DYNAMO_ACCESS_KEY_ID" -var="secret=$DYNAMO_SECRET_ACCESS_KEY" -var="telegram_token=$TELEGRAM_TOKEN"
  
  upload:  
    needs: terraform    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            modify:
              - '**/modify.py'
            send_message:
              - '**/send_message.py'
      
      - name: use zip
        uses: montudor/action-zip@v1
      
      - name: prepare files for modify_data
        if: steps.changes.outputs.modify == 'true'
        run: |
          mkdir upload/modify_data
          cp ./code/new/modify.py ./upload/modify_data/modify.py
      
      - name: build zip for modify_data
        if: steps.changes.outputs.modify == 'true'
        run: |
          cd upload/modify_data
          zip -qq -r modify_data.zip .
          mv modify_data.zip ../../
          
      - name: Deploy to aws function modify_data
        if: steps.changes.outputs.modify == 'true'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: fiemmebot_modify_data_v01
          zip_file: modify_data.zip          
          
      - name: prepare files for send_message
        if: steps.changes.outputs.send_message == 'true'
        run: |
          mkdir upload/send_message
          cp ./code/new/modify.py ./upload/modify_data/modify.py        
          
      - name: build zip for send_message
        if: steps.changes.outputs.send_message == 'true'
        run: |
          cd upload/send_message
          zip -qq -r send_message.zip .
          mv send_message.zip ../../
          
      - name: Deploy to aws function send_message
        if: steps.changes.outputs.send_message == 'true'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: fiemmebot_send_reminder_v01
          zip_file: send_message.zip
          
      

  
            
